/**:
  ros__parameters:
    tool_length: 0.4
    tool_width: 3.0
    tool_center_offset:
      x: -0.4
      y: 0.0
    tool_joint: robot_implement_hitch_joint
    tool_frame: robot_implement_link
    world_frame: map
    joint_state_topic: /robot/implement/joint_states
    implement_pose_topic: /evaluation/robot/implement_pose

    tool_is_outside_period: 3.0  # seconds
    field_headland: 5.0  # meters

    field_names:
      - "mixed_field"
      - "sloping_field"

    fields:
      mixed_field:
        width: 30.0
        height: 9.0
        resolution: 0.2
        position:
          x: 124.242325
          y: 121.087273
          z: 0.98
        rotation:
          r: -0.015
          p: -0.005
          y: -2.79589
      sloping_field:  
        width: 2.5
        height: 50.0
        resolution: 0.2
        position:
          x: 35.48
          y: 213.68
          z: 3.25
        rotation:
          r: 0.01548
          p: -0.3492
          y: 2.0067
